#!/bin/bash

echo "🚀 Phygital Asset NFT API - Railway快速部署脚本"
echo "=============================================="

echo ""
echo "📋 部署前准备："
echo "=============="

# 检查必要文件
if [ ! -f "nft-api-server-amoy.js" ]; then
    echo "❌ 错误：找不到 nft-api-server-amoy.js"
    exit 1
fi

if [ ! -f "package.json" ]; then
    echo "❌ 错误：找不到 package.json"
    exit 1
fi

echo "✅ 部署文件准备就绪"

echo ""
echo "🌐 步骤1：创建GitHub仓库"
echo "========================"
echo "1. 访问 https://github.com"
echo "2. 登录您的GitHub账号"
echo "3. 点击右上角的 '+' 按钮"
echo "4. 选择 'New repository'"
echo "5. 仓库名称：phygital-asset-nft-api"
echo "6. 描述：Phygital Asset NFT API Server for Amoy Testnet"
echo "7. 选择 'Public'"
echo "8. 不要勾选任何选项"
echo "9. 点击 'Create repository'"

echo ""
echo "📤 步骤2：推送代码到GitHub"
echo "=========================="
echo "创建仓库后，GitHub会显示类似这样的URL："
echo "https://github.com/你的用户名/phygital-asset-nft-api.git"
echo ""
echo "请复制这个URL，然后运行以下命令："
echo ""
echo "git remote add origin https://github.com/你的用户名/phygital-asset-nft-api.git"
echo "git push -u origin main"
echo ""
echo "按Enter继续..."
read -p "按Enter继续..."

echo ""
echo "🚂 步骤3：Railway部署"
echo "===================="
echo "1. 访问 https://railway.app"
echo "2. 使用GitHub账号登录"
echo "3. 点击 'New Project'"
echo "4. 选择 'Deploy from GitHub repo'"
echo "5. 选择 'phygital-asset-nft-api' 仓库"

echo ""
echo "⚙️ 步骤4：配置环境变量"
echo "====================="
echo "在Railway Dashboard的Variables标签页添加："
echo ""
echo "AMOY_RPC_URL=https://rpc-amoy.polygon.technology/"
echo "AMOY_CHAIN_ID=80002"
echo "CONTRACT_ADDRESS=0xA0fA27fC547D544528e9BE0cb6569E9B925e533E"
echo "AMOY_PRIVATE_KEY=你的私钥"
echo "NODE_ENV=production"
echo ""
echo "⚠️ 重要：请确保私钥格式正确（64位十六进制）"

echo ""
echo "🚀 步骤5：自动部署"
echo "=================="
echo "Railway会自动："
echo "✅ 检测package.json"
echo "✅ 安装依赖"
echo "✅ 启动服务"
echo "✅ 提供HTTPS URL"

echo ""
echo "📊 步骤6：获取部署URL"
echo "====================="
echo "部署完成后，Railway会提供一个URL，类似："
echo "https://phygital-asset-nft-api-production.up.railway.app"
echo ""
echo "请记录这个URL，稍后需要更新iOS应用配置"

echo ""
echo "🧪 步骤7：测试部署"
echo "================="
echo "使用以下命令测试API："
echo ""
echo "# 健康检查"
echo "curl https://your-railway-url.up.railway.app/api/health"
echo ""
echo "# NFT铸造测试"
echo "curl -X POST https://your-railway-url.up.railway.app/api/mint-thread \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"threadId\":\"test-railway\",\"username\":\"Railway Test\"}'"

echo ""
echo "📱 步骤8：更新iOS应用"
echo "===================="
echo "在 NFTManager.swift 中更新API URL："
echo ""
echo "private let apiURL: String = {"
echo "    #if DEBUG"
echo "    return \"http://127.0.0.1:3000/api\"  // 开发环境"
echo "    #else"
echo "    return \"https://your-railway-url.up.railway.app/api\"  // 生产环境"
echo "    #endif"
echo "}()"

echo ""
echo "✅ 完成！"
echo "========"
echo "现在您的API服务已经："
echo "✅ 运行在Railway云端"
echo "✅ 24/7可用"
echo "✅ 全球可访问"
echo "✅ 自动HTTPS"

echo ""
echo "🎯 下一步："
echo "=========="
echo "1. 完成GitHub仓库创建"
echo "2. 推送代码到GitHub"
echo "3. 在Railway上部署"
echo "4. 测试API功能"
echo "5. 更新iOS应用配置"

echo ""
echo "🚀 开始部署吧！"
