#!/bin/bash
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🧪 Credits系统功能验证"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Market界面Credits显示:"
echo "   - 第28行: @State private var userCredits = 0"
echo "   - 第126行: Text(\"\(userCredits)\")"
echo "   - 第305行: let credits = CreditsManager.shared.getCredits(for: username)"
echo "   - 第308行: self.userCredits = credits"
echo "   - 第250行: await loadUserCredits() in onAppear"
echo ""
echo "✅ CreditsManager功能:"
echo "   - getCredits(username) - 从UserDefaults读取"
echo "   - setCredits(amount, username) - 保存到UserDefaults"
echo "   - transferCredits() - 买卖转账"
echo "   - initializeNewUser() - 新用户1000积分"
echo ""
echo "✅ Bid出价限制:"
echo "   - BidInputView显示Available余额"
echo "   - canSubmit验证: amount <= availableCredits"
echo "   - 余额不足显示红色警告"
echo ""
echo "✅ 交易自动转账:"
echo "   - BidManager.acceptBid完成时"
echo "   - 调用transferCredits()"
echo "   - 买家扣除，卖家增加"
echo ""
echo "测试步骤:"
echo "1. 运行app，登录账号"
echo "2. 打开Market"
echo "3. 查看左上角Credits数字"
echo "4. 应该显示1000（新用户）或实际余额"
echo ""
echo "如果显示0，检查:"
echo "- currentUsername是否正确传入MarketView"
echo "- UserSessionManager.saveSession是否调用过"
echo "- 查看日志: '💰 User credits loaded: X'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
